/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    extend: {
      fontFamily: {
        primary: "sansfarsi",
        
      },
      height: {
        'vh': '100vh',
      },colors: {
        'main': 'rgb(21,21,21)',
        'icon': 'rgb(250,165,61)',
        'sub': 'rgba(21,21,21)',
        'select': 'rgb(50,50,50)',
        'out': 'rgb(246,184,40)',
        'online':'#fa0404'
      },
      backgroundImage: {
        'bg1': "url('aseet/img/8ydem_desktop_1_v1.jpeg')",
        'bg2': "url('aseet/img/88ydem_mobile_1_v1.jpeg')",
        'bg3': "url('aseet/img/b0jfc_desktop_1_v1.jpeg')",
        'bg4': "url('aseet/img/b0jfc_mobile_1_v1.jpeg')",
        'bg5': "url('aseet/img/b7zgp_desktop_1_v1.jpeg')",
        'bg6': "url('aseet/img/b777zgp_mobile_1_v1.jpeg')",
        'mv1': "url('aseet/img/mov_147472_169769.jpg')",
        'mv2': "url('aseet/img/mov_147582_169765.jpg')",
        'mv3': "url('aseet/img/mov_147719_184195.jpg')",
        'mv4': "url('aseet/img/mov_147945_182865.jpg')",
        'mv5': "url('aseet/img/mov_148573_183522.jpg')",
        'mv6': "url('aseet/img/f.jpg')",
        'mv7': "url('aseet/img/mov_148810_184200.jpg')",
        'mv8': "url('aseet/img/mov_148811_184355.jpg')",
        'mv9': "url('aseet/img/mov_148825_184091.jpg')",
        'mv10': "url('aseet/img/d.jpg')",
        'mv11': "url('aseet/img/a.jpg')",
        'mv12': "url('aseet/img/mov_148908_184429.jpg')",
        'mv13': "url('aseet/img/mov_148911_184431.jpg')",
        'mv14': "url('aseet/img/mov_148913_184427.jpg')",
        'mv15': "url('aseet/img/mov_148930_184359.jpg')",
        'mv16': "url('aseet/img/mov_1561_184447.jpg')",
        'mv17': "url('aseet/img/mov_1561_184447.jpg')",
        'mv18': "url('aseet/img/a.jpg')",
        'mv19': "url('aseet/img/b.jpg')",
        'mv20': "url('aseet/img/c.jpg')",
        'mv21': "url('aseet/img/e.jpg')",
        'mv22': "url('aseet/img/f.jpg')",
        'slide1': "url('aseet/img/o.jpg')",
        'slide2': "url('aseet/img/u.jpg')",
        'slide3': "url('aseet/img/p.jpg')",
        'slide4': "url('aseet/img/x.jpg')",
        'slide5': "url('aseet/img/g.jpg')",
        'slide6': "url('aseet/img/i.jpg')",
        'slide7': "url('aseet/img/h.jpg')",
        'slide8': "url('aseet/img/g.jpg')",
        'slide9': "url('aseet/img/o.jpg')",
        'slide10': "url('aseet/img/u.jpg')",
        'slide11': "url('aseet/img/p.jpg')",
        'slide12': "url('aseet/img/x.jpg')",
        'slide13': "url('aseet/img/g.jpg')",
        'slide14': "url('aseet/img/i.jpg')",
        'slide15': "url('aseet/img/h.jpg')",
        'slide16': "url('aseet/img/')",
        'slide17': "url('aseet/img/1.jpg')",
        'slide18': "url('aseet/img/2.jpg')",
        'slide19': "url('aseet/img/3.jpg')",
        'slide20': "url('aseet/img/4.jpg')",
        'slide21': "url('aseet/img/5.jpg')",
        'slide22': "url('aseet/img/6.jpg')",
        'slide23': "url('aseet/img/7.jpg')",
        'slide24': "url('aseet/img/8.jpg')",
        'slide25': "url('aseet/img/9.jpg')",
        'slide26': "url('aseet/img/10.jpg')",
        'slide27': "url('aseet/img/11.jpg')",
        'slide28': "url('aseet/img/12.jpg')",
        'slide29': "url('aseet/img/13.jpg')",
        'slide30': "url('aseet/img/14.jpg')",
        'slide31': "url('aseet/img/15.jpg')",
        'slide32': "url('aseet/img/16.jpg')",
        'slide33': "url('aseet/img/66.webp')",
      
      }
    },
    animation: {
      'ease': 'ease',
    }
  },
  plugins: [],
}

